In [ ]:
#numpy is a numerical matrix calculation library

# converting standard array to np array
# some common functions
# operators

In [3]:
marks=[10,20,30,40,50,60]

# new_marks=marks+10


new_marks=[]
for mark in marks:
    new_marks.append(mark+10)

print(new_marks)

[20, 30, 40, 50, 60, 70]


In [4]:
import numpy as np

marks=np.array([10,20,30,40,50,60])
new_marks=marks+10

print(new_marks)

[20 30 40 50 60 70]


In [5]:
#evaluate total marks
marks=np.array([10,20,30,40,50,60])

total_marks=np.sum(marks)
print(total_marks)

210


In [6]:
#convert a standard array to a numpy array

product_prices=[100,200,300,400,500] #standard array

print(type(product_prices)) #list


pp=np.array(product_prices) #numpy array

print(type(pp)) #numpy.ndarray

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
#common functions

prices=np.array([100,200,300,400,500])
print(np.mean(prices))
print(np.median(prices))
print(np.std(prices))
print(np.sum(prices))
print(np.min(prices))
print(np.max(prices))

300.0
300.0
141.4213562373095
1500
100
500


In [ ]:
#matrix
data=[[10,20],[30,40]]
print(data)

[[10, 20], [30, 40]]


In [9]:
data=np.array([[10,20],[30,40]])
print(data)

[[10 20]
 [30 40]]


In [10]:
a1=np.array([[10,20],[30,40]])
a2=np.array([[1,2],[3,4]])

a3=a1*a2

print(a3)

[[ 10  40]
 [ 90 160]]


In [11]:
np.dot(a1,a2)

array([[ 70, 100],
       [150, 220]])

In [22]:
#shape (3,4)
print(np.ones((3,4)))
print()
print(np.zeros((3,4)))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [40]:
x=np.random.rand(5,5)
x=(x*50).astype(int)
print(x)

[[33  6 26  8 32]
 [11 40 40 43  8]
 [26 35 21  6 25]
 [37 18 36 32 21]
 [11 20 19 15 28]]


In [42]:
y=x[:3,:3]
print(y)

[[33  6 26]
 [11 40 40]
 [26 35 21]]


In [ ]:
marks=np.array([10,20,30,40,50,60])
m2=marks[:3]
print(m2)

[10 20 30]


In [43]:
x=np.random.rand(5,4)
x=(x*50).astype(int)
print(x)

[[23 18 49 21]
 [31 10 11 46]
 [30 11 31 28]
 [37 25  2 45]
 [37 41 28 17]]


In [44]:
print(x.shape)

(5, 4)


In [45]:
z=x.reshape(10,2)
print(z)

[[23 18]
 [49 21]
 [31 10]
 [11 46]
 [30 11]
 [31 28]
 [37 25]
 [ 2 45]
 [37 41]
 [28 17]]


In [48]:
a=z.flatten()
print(a)

[23 18 49 21 31 10 11 46 30 11 31 28 37 25  2 45 37 41 28 17]


In [50]:
c=np.array([[0,1,2],[3,4,5],[6,7,8]])
print(c)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
d=c.T
print(d)

[[0 3 6]
 [1 4 7]
 [2 5 8]]
