In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [36]:
df=pd.read_csv('titatnic.csv')

df.head()

Passengerid   Age     Fare  Sex  ...  Embarked  zero.17  zero.18  2urvived
0            1  22.0   7.2500    0  ...       2.0        0        0         0
1            2  38.0  71.2833    1  ...       0.0        0        0         1
2            3  26.0   7.9250    1  ...       2.0        0        0         1
3            4  35.0  53.1000    1  ...       2.0        0        0         1
4            5  35.0   8.0500    0  ...       2.0        0        0         0

[5 rows x 28 columns]

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [38]:
df.describe()

Passengerid          Age         Fare  ...  zero.17  zero.18     2urvived
count  1309.000000  1309.000000  1309.000000  ...   1309.0   1309.0  1309.000000
mean    655.000000    29.503186    33.281086  ...      0.0      0.0     0.261268
std     378.020061    12.905241    51.741500  ...      0.0      0.0     0.439494
min       1.000000     0.170000     0.000000  ...      0.0      0.0     0.000000
25%     328.000000    22.000000     7.895800  ...      0.0      0.0     0.000000
50%     655.000000    28.000000    14.454200  ...      0.0      0.0     0.000000
75%     982.000000    35.000000    31.275000  ...      0.0      0.0     1.000000
max    1309.000000    80.000000   512.329200  ...      0.0      0.0     1.000000

[8 rows x 28 columns]

In [39]:
df.columns

Index(['Passengerid', 'Age', 'Fare', 'Sex', 'sibsp', 'zero', 'zero.1',
       'zero.2', 'zero.3', 'zero.4', 'zero.5', 'zero.6', 'Parch', 'zero.7',
       'zero.8', 'zero.9', 'zero.10', 'zero.11', 'zero.12', 'zero.13',
       'zero.14', 'Pclass', 'zero.15', 'zero.16', 'Embarked', 'zero.17',
       'zero.18', '2urvived'],
      dtype='object')

In [40]:
df2=df[['Age', 'Fare', 'Sex', 'sibsp','Pclass','Embarked', '2urvived']]

df2.rename(columns={'2urvived':'Survived'}, inplace=True)   

df2.head()

/var/folders/5g/7m5tb_kn729bgtcb25k58dlc0000gn/T/ipykernel_39535/3938704720.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.rename(columns={'2urvived':'Survived'}, inplace=True)


Age     Fare  Sex  sibsp  Pclass  Embarked  Survived
0  22.0   7.2500    0      1       3       2.0         0
1  38.0  71.2833    1      1       1       0.0         1
2  26.0   7.9250    1      0       3       2.0         1
3  35.0  53.1000    1      1       1       2.0         1
4  35.0   8.0500    0      0       3       2.0         0

In [41]:
df2.isnull().sum()
df2.dropna(inplace=True)
df2.isnull().sum()

/var/folders/5g/7m5tb_kn729bgtcb25k58dlc0000gn/T/ipykernel_39535/11987178.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(inplace=True)


Age         0
Fare        0
Sex         0
sibsp       0
Pclass      0
Embarked    0
Survived    0
dtype: int64

In [42]:
df2['Survived'].value_counts()


Survived
0    967
1    340
Name: count, dtype: int64

In [43]:
y=df2['Survived']
x=df2.drop('Survived', axis=1)

In [44]:
#split dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=42)


In [45]:
y_train.value_counts()

Survived
0    729
1    251
Name: count, dtype: int64

In [46]:
#logistics regression
#random forest
#naives bayes

In [ ]:
#logistic regression model
from pyexpat import model
from sklearn.linear_model import LogisticRegression
lr_model=LogisticRegression()

lr_model.fit(x_train, y_train) #training step

y_pred=lr_model.predict(x_test)

#evaluation

accuracy=accuracy_score(y_test, y_pred)
confusion=confusion_matrix(y_test, y_pred)
report=classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", report)

Accuracy: 0.7859327217125383
Confusion Matrix:
 [[223  15]
 [ 55  34]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.94      0.86       238
           1       0.69      0.38      0.49        89

    accuracy                           0.79       327
   macro avg       0.75      0.66      0.68       327
weighted avg       0.77      0.79      0.76       327



In [56]:
#naive bayes
from sklearn.naive_bayes import GaussianNB
nb_model=GaussianNB()   

nb_model.fit(x_train, y_train) #training step

y_pred_nb=nb_model.predict(x_test)

#evaluation
accuracy_nb=accuracy_score(y_test, y_pred_nb)
confusion_nb=confusion_matrix(y_test, y_pred_nb)
report_nb=classification_report(y_test, y_pred_nb)
print("Accuracy:", accuracy_nb)
print("Confusion Matrix:\n", confusion_nb)
print("Classification Report:\n", report_nb)



Accuracy: 0.7614678899082569
Confusion Matrix:
 [[221  17]
 [ 61  28]]
Classification Report:
               precision    recall  f1-score   support

           0       0.78      0.93      0.85       238
           1       0.62      0.31      0.42        89

    accuracy                           0.76       327
   macro avg       0.70      0.62      0.63       327
weighted avg       0.74      0.76      0.73       327



In [57]:
#random forest model
from sklearn.ensemble import RandomForestClassifier
rf_model=RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(x_train, y_train) #training step

y_pred_rf=rf_model.predict(x_test)

#evaluation
accuracy_rf=accuracy_score(y_test, y_pred_rf)
confusion_rf=confusion_matrix(y_test, y_pred_rf)
report_rf=classification_report(y_test, y_pred_rf)

print("Accuracy:", accuracy_rf)
print("Confusion Matrix:\n", confusion_rf)
print("Classification Report:\n", report_rf)


Accuracy: 0.7706422018348624
Confusion Matrix:
 [[206  32]
 [ 43  46]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.87      0.85       238
           1       0.59      0.52      0.55        89

    accuracy                           0.77       327
   macro avg       0.71      0.69      0.70       327
weighted avg       0.76      0.77      0.77       327



In [58]:
#grid tune random forest model
from sklearn.model_selection import GridSearchCV
param_grid = {
    'n_estimators': [10, 20, 40],
    'max_depth': [3,4,5,6,7],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 3, 4],
}

#num combinations
param_grid['n_estimators'].__len__()*param_grid['max_depth'].__len__()*param_grid['min_samples_split'].__len__()*param_grid['min_samples_leaf'].__len__()



180

In [ ]:
grid_search = GridSearchCV(estimator=rf_model, param_grid=param_grid, cv=5, n_jobs=-1, verbose=2)
grid_search.fit(x,y)
best_params = grid_search.best_params_


Fitting 5 folds for each of 180 candidates, totalling 900 fits
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=10; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_samples_split=2, n_estimators=20; total time=   0.0s
[CV] END max_depth=3, min_samples_leaf=1, min_

In [60]:
best_params 

{'max_depth': 6,
 'min_samples_leaf': 3,
 'min_samples_split': 10,
 'n_estimators': 40}

In [ ]:
models=grid_search.best_estimator_ #best model after grid search

grid_search.best_score_

np.float64(0.7910678248661929)

In [62]:
final_model=RandomForestClassifier(max_depth= 6, min_samples_leaf= 3, min_samples_split= 10, n_estimators= 40)
final_model.fit(x_train, y_train)
y_final_pred=final_model.predict(x_test)
accuracy_final=accuracy_score(y_test, y_final_pred)
confusion_final=confusion_matrix(y_test, y_final_pred)
report_final=classification_report(y_test, y_final_pred)
print("Accuracy:", accuracy_final)
print("Confusion Matrix:\n", confusion_final)
print("Classification Report:\n", report_final)


Accuracy: 0.7951070336391437
Confusion Matrix:
 [[220  18]
 [ 49  40]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.92      0.87       238
           1       0.69      0.45      0.54        89

    accuracy                           0.80       327
   macro avg       0.75      0.69      0.71       327
weighted avg       0.78      0.80      0.78       327



In [63]:
df2.head()

Age     Fare  Sex  sibsp  Pclass  Embarked  Survived
0  22.0   7.2500    0      1       3       2.0         0
1  38.0  71.2833    1      1       1       0.0         1
2  26.0   7.9250    1      0       3       2.0         1
3  35.0  53.1000    1      1       1       2.0         1
4  35.0   8.0500    0      0       3       2.0         0

In [ ]:
#new prediction
prediction=final_model.predict([[50,30,3,1,2,0]])
print(prediction)

[0]


/Users/nirmal/.pyenv/versions/3.12.2/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
